const wilayas = [
    {name: "Adrar", nom_ar: "أدرار"},
    {name: "Laghouat", nom_ar: "الأغواط"},
    {name: "Chlef", nom_ar: "الشلف"},
    {name: "Oum El Bouaghi", nom_ar: "أم البواقي"},
    {name: "Batna", nom_ar: "باتنة"},
    {name: "Béjaïa", nom_ar: "بجاية"},
    {name: "Biskra", nom_ar: "بسكرة"},
    {name: "Béchar", nom_ar: "بشار"},
    {name: "Blida", nom_ar: "البليدة"},
    {name: "Bouira", nom_ar: "البويرة"},
    {name: "Tamanrasset", nom_ar: "تمنراست"},
    {name: "Tébessa", nom_ar: "تبسة"},
    {name: "Tlemcen", nom_ar: "تلمسان"},
    {name: "Tiaret", nom_ar: "تيارت"},
    {name: "Tizi Ouzou", nom_ar: "تيزي وزو"},
    {name: "Alger", nom_ar: "الجزائر"},
    {name: "Djelfa", nom_ar: "الجلفة"},
    {name: "Jijel", nom_ar: "جيجل"},
    {name: "Sétif", nom_ar: "سطيف"},
    {name: "Saïda", nom_ar: "سعيدة"},
    {name: "Skikda", nom_ar: "سكيكدة"},
    {name: "Sidi Bel Abbès", nom_ar: "سيدي بلعباس"},
    {name: "Annaba", nom_ar: "عنابة"},
    {name: "Guelma", nom_ar: "قالمة"},
    {name: "Constantine", nom_ar: "قسنطينة"},
    {name: "Médéa", nom_ar: "المدية"},
    {name: "Mostaganem", nom_ar: "مستغانم"},
    {name: "M'Sila", nom_ar: "المسيلة"},
    {name: "Mascara", nom_ar: "معسكر"},
    {name: "Ouargla", nom_ar: "ورقلة"},
    {name: "Oran", nom_ar: "وهران"},
    {name: "El Bayadh", nom_ar: "البيض"},
    {name: "Illizi", nom_ar: "إليزي"},
    {name: "Bordj Bou Arreridj", nom_ar: "برج بوعريريج"},
    {name: "Boumerdès", nom_ar: "بومرداس"},
    {name: "El Tarf", nom_ar: "الطارف"},
    {name: "Tindouf", nom_ar: "تندوف"},
    {name: "Tissemsilt", nom_ar: "تيسمسيلت"},
    {name: "El Oued", nom_ar: "الوادي"},
    {name: "Khenchela", nom_ar: "خنشلة"},
    {name: "Souk Ahras", nom_ar: "سوق أهراس"},
    {name: "Tipaza", nom_ar: "تيبازة"},
    {name: "Mila", nom_ar: "ميلة"},
    {name: "Aïn Defla", nom_ar: "عين الدفلة"},
    {name: "Naâma", nom_ar: "النعامة"},
    {name: "Aïn Témouchent", nom_ar: "عين تيموشنت"},
    {name: "Ghardaïa", nom_ar: "غرداية"},
    {name: "Relizane", nom_ar: "غليزان"},
    {name: "Timimoun", nom_ar: "تيميمون"},
    {name: "Bordj Badji Mokhtar", nom_ar: "برج باجي مختار"},
    {name: "Ouled Djellal", nom_ar: "أولاد جلال"},
    {name: "Béni Abbès", "nom_ar": "بني عباس"},
    {name: "In Salah", nom_ar: "عين صالح"},
    {name: "In Guezzam", nom_ar: "عين قزام"},
    {name: "Touggourt", nom_ar: "تقرت"},
    {name: "Djanet", nom_ar: "جانت"},
    {name: "El Meghaier", nom_ar: "المغير"},
    {name: "El Menia", nom_ar: "المنيعة"}
  ]

  export default wilayas;